chore: add issue and pr templates
eludris/pengin pull request #13
Opened 2023-01-26 20:12 UTC by toolifelesstocode

## Description

This adds PR and Issue templates to the repo. They are very similar to https://github.com/eludris/eludris 's templates.

2023-01-26 20:16 UTC, EnokiUN requested changes

2023-01-26 20:16 UTC, EnokiUN commented on .github/ISSUE_TEMPLATES/bug_report.yml
> +        Include console output, if any
```suggestion
        Additionally, include console output, if any
```

2023-01-26 20:16 UTC, EnokiUN commented on .github/ISSUE_TEMPLATES/bug_report.yml
> +      label: Minimum Reproducible Steps
```suggestion
      label: Minimum Reproduction Steps
```

2023-01-26 20:16 UTC, EnokiUN commented on .github/ISSUE_TEMPLATES/bug_report.yml
> +        Insert any images/videos of the issue.
```suggestion
        Insert any images/videos of the issue
```

2023-01-26 20:16 UTC, EnokiUN commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] This has been previewed and's output is as intended
```suggestion
- [ ] This has been previewed and looks as intended
```

2023-01-27 14:49 UTC, EnokiUN approved these changes

2023-01-28 20:30 UTC, merged

2023-01-29 18:33 UTC, toolifelesstocode commented on .github/ISSUE_TEMPLATES/bug_report.yml
> +        - label: Have you checked the documentation?
Pengin has no docs :neckbeard: